//
//  DetailBeerWireframe.swift
//  BeerViper
//
//  Created by Emil Shpeklord on 09.07.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum DetailBeerAssembly {
    static func build(data: Beer.InitForm.ViewModel) -> UIViewController {
        let view = DetailBeerViewController()
        let presenter = DetailBeerPresenter(view: view)
        let interactor = DetailBeerInteractor(presenter: presenter)

        view.presenter = presenter
        presenter.interactor = interactor

        presenter.data = data
        return view
    }
}
