//
//  DetailBeerInterfaces.swift
//  BeerViper
//
//  Created by Emil Shpeklord on 09.07.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit


protocol DetailBeerViewProtocol: AnyObject {
}

protocol DetailBeerPresenterProtocol: AnyObject {
}

protocol DetailBeerInteractorProtocol: AnyObject {
}
